apiVersion: apps/v1
kind: Deployment
metadata:
  name: jdggws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdggws
  template:
    metadata:
      labels:
        app: jdggws
    spec:
      containers:
      - image: okteto.dev/jdggws:latest
        name: jdggws
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "57d5660c-295c-4b26-9535-776fb270f997"
        - name: Vless_Path
          value: "/vl5ng55"
        - name: Vmess_UUID
          value: "57d5660c-295c-4b26-9535-776fb270f997"
        - name: Vmess_Path
          value: "/vm6dn66"
        - name: Share_Path
          value: "/v2link"
